### ISSUE TITLE
Guess the Number Game

### ISSUE THREAD

**Issue by Pratyay008** [Priyadarshan2000/Hacktoberfest_2k22#47]
# Guess the Number Game
@Priyadarshan2000  I want to make a 'Guess the Number' project using python and file handling. Please assign me this issue.

**Comment by Priyadarshan2000** [comment]
@Pratyay008 ho ahead bro 👍

**Comment by Pratyay008** [comment]
@Priyadarshan2000  This issue is resolved now, should I close this issue as completed?

**Comment by Ak8933** [comment]
hey @Priyadarshan2000 can u assign this issue to me?

**Comment by Priyadarshan2000** [comment]
> @Priyadarshan2000 This issue is resolved now, should I close this issue as completed?

ya sure bro

**Comment by Pratyay008** [comment]
@Priyadarshan2000  Okay

**Comment by Priyadarshan2000** [comment]
> hey @Priyadarshan2000 can u assign this issue to me?

bro this issue  already assigned.
