### ISSUE TITLE
Rock Paper Scissors Game

### ISSUE THREAD

**Issue by Pratyay008** [Priyadarshan2000/Hacktoberfest_2k22#91]
@Priyadarshan2000  I want to contribute to a 'Rock Paper Scissors' Game in python. Please assign me to this issue.

**Comment by Priyadarshan2000** [comment]
@Pratyay008  go ahed 👍

**Comment by sona-123** [comment]
Hello Sir I want to contribute to this Rock paper scissor game in C++. Please assign this issue to me.
